[workspace]
authors = ["Luan Leal <luanleal@usp.br>"]
channels = ["conda-forge", "bioconda"]
name = "PlasmidEvo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.9.*"
seqkit = ">=2.10.1,<3"
biopython = ">=1.85,<2"
memory_profiler = ">=0.61.0,<0.62"
jupyterlab = ">=4.4.5,<5"
needletail = ">=0.7.0,<0.8"
pyrodigal = ">=3.6.3.post1, <4"
click = ">=8.1.8,<9"
diamond = ">=2.1.13,<3"
file-read-backwards = ">=3.2.0,<4"
polars = ">=1.32.3,<2"
matplotlib = ">=3.9.4,<4"
numpy = ">=2.0.2,<3"
ruff = ">=0.12.11,<0.13"
ruff-lsp = ">=0.0.62,<0.0.63"
python-lsp-server = ">=1.13.1,<2"
pyright = ">=1.1.403,<2"
pylint = ">=3.3.8,<4"
igraph = ">=0.10.16,<0.11"
python-igraph = ">=0.11.9,<0.12"
pycairo = ">=1.28.0,<2"
leidenalg = ">=0.10.2,<0.11"
bakta = ">=1.11.4,<2"

[pypi-dependencies]
infomap = ">=2.8.0, <3"
